Paho/Controllers/ColonyController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using Resources.Abstract;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Paho.Models;

namespace Paho.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ColonyController : ControllerBase
    {
        private int _pageSize = 10;

        // GET: Colony
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            var countryId = user.Institution.CountryID ?? 0;
            //var colonies = db.Colonies.Include(p => p.Hamlet);

            //****
            ViewBag.CurrentSort = sortOrder;
            ViewBag.AreaParm = "areaName";
            ViewBag.StateParm = "stateName";
            ViewBag.NeighborhoodParm = "neighborhoodName";
            ViewBag.HamletParm = "hamletName";
            ViewBag.ColonyParm = "colonyName";
            //ViewBag.OrigCountryParm = "origCountry";

            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;

            var catalogo = from c in db.Colonies where c.Hamlet.Neighborhood.State.Area.CountryID == countryId select c;
            if (!string.IsNullOrEmpty(searchString))
            {
                catalogo = catalogo.Where(s => s.Name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "areaName":
                    catalogo = catalogo.OrderBy(s => s.Hamlet.Neighborhood.State.Area.Name).ThenBy(s => s.Hamlet.Neighborhood.State.Name)
                                    .ThenBy(s => s.Hamlet.Neighborhood.Name).ThenBy(s => s.Hamlet.Name).ThenBy(s => s.Name);
                    break;
                case "stateName":
                    catalogo = catalogo.OrderBy(s => s.Hamlet.Neighborhood.State.Name).ThenBy(s => s.Hamlet.Neighborhood.Name)
                                    .ThenBy(s => s.Hamlet.Name).ThenBy(s => s.Name);
                    break;
                case "neighborhoodName":
                    catalogo = catalogo.OrderBy(s => s.Hamlet.Neighborhood.Name).ThenBy(s => s.Hamlet.Name).ThenBy(s => s.Name);
                    break;
                case "hamletName":
                    catalogo = catalogo.OrderBy(s => s.Hamlet.Name).ThenBy(s => s.Name);
                    break;
                case "colonyName":
                    catalogo = catalogo.OrderBy(s => s.Name);
                    break;
                case "origCountry":
                    catalogo = catalogo.OrderBy(s => s.orig_country);
                    break;
                default:
                    catalogo = catalogo.OrderBy(s => s.Hamlet.Neighborhood.State.Area.Name).ThenBy(s => s.Hamlet.Neighborhood.State.Name)
                                    .ThenBy(s => s.Hamlet.Neighborhood.Name).ThenBy(s => s.Hamlet.Name).ThenBy(s => s.Name);
                    break;
            }

            //****
            if (user.Institution.AccessLevel == AccessLevel.Country || user.Institution.AccessLevel == AccessLevel.SelfOnly || user.Institution.AccessLevel == AccessLevel.Service)
            {
                if (user.Institution.AccessLevel == AccessLevel.Country)
                {
                    catalogo = catalogo.Where(s => s.Hamlet.Neighborhood.State.Area.CountryID == user.Institution.CountryID);
                    /*.OrderBy(o => o.Hamlet.Neighborhood.State.Area.Country.Name).ThenBy(o => o.Hamlet.Neighborhood.State.Area.Name)
                    .ThenBy(o => o.Hamlet.Neighborhood.State.Name).ThenBy(o => o.Hamlet.Neighborhood.Name)
                    .ThenBy(o => o.Hamlet.Name).ThenBy(o => o.Name);*/
                }
                else if (user.Institution.AccessLevel == AccessLevel.SelfOnly || user.Institution.AccessLevel == AccessLevel.Service)
                {
                    catalogo = catalogo.Where(s => s.Hamlet.Neighborhood.State.Area.CountryID == user.Institution.CountryID);
                    /*.OrderBy(o => o.Hamlet.Neighborhood.State.Area.Country.Name).ThenBy(o => o.Hamlet.Neighborhood.State.Area.Name)
                    .ThenBy(o => o.Hamlet.Neighborhood.State.Name).ThenBy(o => o.Hamlet.Neighborhood.Name)
                    .ThenBy(o => o.Hamlet.Name).ThenBy(o => o.Name);*/
                }
            }
            else if (user.Institution.AccessLevel == AccessLevel.Area)
            {
                catalogo = catalogo.Where(s => s.Hamlet.Neighborhood.State.Area.CountryID == user.Institution.CountryID);
            }

            int pageSize = _pageSize;
            int pageNumber = (page ?? 1);

            //return View(colonies.ToList());
            return View(catalogo.ToPagedList(pageNumber, pageSize));
        }

        // GET: Hamlet/Create
        public ActionResult Create()
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            var UsrLang = user.Institution.Country.Language;

            //****
            var cat_countries = from c in db.Countries select c;
            if (user.Institution.AccessLevel == AccessLevel.Country || user.Institution.AccessLevel == AccessLevel.SelfOnly || user.Institution.AccessLevel == AccessLevel.Service)
            {
                if (user.Institution.AccessLevel == AccessLevel.Country)
                {
                    cat_countries = cat_countries.Where(s => s.ID == user.Institution.CountryID);
                }
                else if (user.Institution.AccessLevel == AccessLevel.SelfOnly || user.Institution.AccessLevel == AccessLevel.Service)
                {
                    cat_countries = cat_countries.Where(s => s.ID == user.Institution.CountryID);
                }
            }
            else if (user.Institution.AccessLevel == AccessLevel.Area)
            {
                cat_countries = cat_countries.Where(s => s.ID == user.Institution.CountryID);
            }

            ViewBag.Countries = new SelectList(cat_countries, "ID", "Name");

            //****
            var areas = db.Areas.Include(a => a.Country);

            if (user.Institution.AccessLevel == AccessLevel.Country || user.Institution.AccessLevel == AccessLevel.SelfOnly || user.Institution.AccessLevel == AccessLevel.Service)
            {
                if (user.Institution.AccessLevel == AccessLevel.Country)
                {
                    areas = areas.Where(s => s.CountryID == user.Institution.CountryID)
                                    .OrderBy(o => o.Country.Name).ThenBy(o => o.Name);
                }
                else if (user.Institution.AccessLevel == AccessLevel.SelfOnly || user.Institution.AccessLevel == AccessLevel.Service)
                {
                    areas = areas.Where(s => s.CountryID == user.Institution.CountryID)
                                    .OrderBy(o => o.Country.Name).ThenBy(o => o.Name);
                }
            }
            else if (user.Institution.AccessLevel == AccessLevel.Area)
            {
                areas = areas.Where(s => s.CountryID == user.Institution.CountryID);
            }

            ViewBag.Areas = new SelectList(areas, "ID", "Name");

            //****
            return View();
        }

        // POST: Colony/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID, HamletID, Name, orig_country, Latitude, Longitude")] Colony colony)
        {
            if (ModelState.IsValid)
            {
                db.Colonies.Add(colony);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.CountryID = new SelectList(db.Countries, "ID", "Code", area.CountryID);           //???????
            return View(colony);
        }

        // GET: Colony/Edit/5
        public ActionResult Edit(int? id)
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            var UsrLang = user.Institution.Country.Language;
            //****
            var cat_countries = from c in db.Countries select c;
            if (user.Institution.AccessLevel == AccessLevel.Country || user.Institution.AccessLevel == AccessLevel.SelfOnly || user.Institution.AccessLevel == AccessLevel.Service)
            {
                if (user.Institution.AccessLevel == AccessLevel.Country)
                {
                    cat_countries = cat_countries.Where(s => s.ID == user.Institution.CountryID);
                }
                else if (user.Institution.AccessLevel == AccessLevel.SelfOnly || user.Institution.AccessLevel == AccessLevel.Service)
                {
                    cat_countries = cat_countries.Where(s => s.ID == user.Institution.CountryID);
                }
            }
            else if (user.Institution.AccessLevel == AccessLevel.Area)
            {
                cat_countries = cat_countries.Where(s => s.ID == user.Institution.CountryID);
            }

            ViewBag.Countries = new SelectList(cat_countries, "ID", "Name");

            //****
            var cat_areas = db.Areas.Include(a => a.Country);

            if (user.Institution.AccessLevel == AccessLevel.Country || user.Institution.AccessLevel == AccessLevel.SelfOnly || user.Institution.AccessLevel == AccessLevel.Service)
            {
                if (user.Institution.AccessLevel == AccessLevel.Country)
                {
                    cat_areas = cat_areas.Where(s => s.CountryID == user.Institution.CountryID)
                                    .OrderBy(o => o.Country.Name).ThenBy(o => o.Name);

Paho/Views/Colony/Create.cshtml
@model Paho.Models.Colony
@{ 
    string labelLatitude = Paho.Controllers.ResourcesM.SgetMessage("msgLatitude", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelLongitude = Paho.Controllers.ResourcesM.SgetMessage("msgLongitude", ViewBag.UsrCtry, ViewBag.UsrCtryLang);

    string labelSelect = Paho.Controllers.ResourcesM.SgetMessage("msgSelectLabel", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelColony = Paho.Controllers.ResourcesM.SgetMessage("msgCaselistVigTabGeoLabelColony", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelOrigCountry = Paho.Controllers.ResourcesM.SgetMessage("msgCaselistVigTabGeoLabelOrigCountry", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@(((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelColony"))</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!-- Country -->
        <div class="form-group">
            @Html.LabelFor(model => model.Hamlet.Neighborhood.State.Area.CountryID, (((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelCountry")),
                            htmlAttributes: new { @class = "control-label col-md-1_5" })
            <div class="col-md-7">
                @Html.DropDownList("CountryID", ViewBag.Countries as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Hamlet.Neighborhood.State.Area.CountryID, "", new { @class = "text-danger" })
            </div>
        </div>
        <!-- AreaID -->
        <div class="form-group">
            @Html.LabelFor(model => model.Hamlet.Neighborhood.State.AreaID, (((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelArea")),
                            htmlAttributes: new { @class = "control-label col-md-1_5" })
            <div class="col-md-7">
                @Html.DropDownList("AreaID", ViewBag.Areas as SelectList, (((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgSelectLabel")),
                            htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Hamlet.Neighborhood.State.AreaID, "", new { @class = "text-danger" })
            </div>
        </div>
        <!-- StateID -->
        <div class="form-group">
            @Html.LabelFor(model => model.Hamlet.Neighborhood.StateID, (((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelState")),
                            htmlAttributes: new { @class = "control-label col-md-1_5" })
            <div class="col-md-7">
                @Html.DropDownList("StateID", new SelectList(" "), (((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgSelectLabel")),
                            htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Hamlet.Neighborhood.StateID, "", new { @class = "text-danger" })
            </div>
        </div>
        <!-- NeighborhoodID -->
        <div class="form-group">
            @Html.LabelFor(model => model.Hamlet.NeighborhoodID, (((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelNeighborhood")),
                            htmlAttributes: new { @class = "control-label col-md-1_5" })
            <div class="col-md-7">
                @Html.DropDownList("NeighborhoodID", new SelectList(" "), (((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgSelectLabel")),
                            htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Hamlet.NeighborhoodID, "", new { @class = "text-danger" })
            </div>
        </div>
        <!-- HamletID -->
        <div class="form-group">
            @Html.LabelFor(model => model.HamletID, (((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelHamlet")),
                            htmlAttributes: new { @class = "control-label col-md-1_5" })
            <div class="col-md-7">
                @Html.DropDownList("HamletID", new SelectList(" "), (((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgSelectLabel")),
                            htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HamletID, "", new { @class = "text-danger" })
            </div>
        </div>
        <!-- Barrio/Colonia -->
        <div class="form-group">
            @Html.LabelFor(model => model.Name, labelColony, htmlAttributes: new { @class = "control-label col-md-1_5" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <!-- Latitud -->
        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, labelLatitude, htmlAttributes: new { @class = "control-label col-md-1_5" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <!-- Longitud -->
        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, labelLongitude, htmlAttributes: new { @class = "control-label col-md-1_5" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <!-- orig_country -->
        <div class="form-group">
            @Html.LabelFor(model => model.orig_country, htmlAttributes: new { @class = "control-label col-md-1_5" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.orig_country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.orig_country, "", new { @class = "text-danger" })
            </div>
        </div>
        <!-- Boton: sbmit -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    function limpiarCampos(opcion) {
        if (opcion == "Area") {
            $("#StateID").val("");
            $("#NeighborhoodID").val("");
            $("#HamletID").val("");
        }
        else if (opcion == "State") {
            $("#NeighborhoodID").val("");
            $("#HamletID").val("");
        }
        else if (opcion == "Hamlet") {
            $("#HamletID").val("");
        }

        $("#Name").val("");
        $("#orig_country").val("");
    }

    $(document).ready(function () {
        $("#AreaID").change(function () {       // Area : Departamento
            $.get("/cases/GetStates", { AreaID: $("#AreaID").val() }, function (data) {
                $("#StateID").empty();
                $("#StateID").append("<option value=''>" + "@(labelSelect)" + "</option>")
                $.each(data, function (index, row) {
                    $("#StateID").append("<option value='" + row.Id + "'>" + row.Name + "</option>")
                });

                $("#NeighborhoodID").empty();
                $("#NeighborhoodID").append("<option value=''>" + "@(labelSelect)" + "</option>")
                $("#HamletID").empty();
                $("#HamletID").append("<option value=''>" + "@(labelSelect)" + "</option>")

                limpiarCampos("");
            });
        });

        $("#StateID").change(function () {      //  State : Municipio
            $.get("/cases/GetNeighborhoods", { StateID: $("#StateID").val() }, function (data) {
                $("#NeighborhoodID").empty();
                $("#NeighborhoodID").append("<option value=''>" + "@(labelSelect)" + "</option>")
                $.each(data, function (index, row) {
                    $("#NeighborhoodID").append("<option value='" + row.Id + "'>" + row.Name + "</option>")
                });

                $("#HamletID").empty();
                $("#HamletID").append("<option value=''>" + "@(labelSelect)" + "</option>")

                limpiarCampos("");
            });
        });

        $("#NeighborhoodID").change(function () {      //  Neighborhood : Aldea
            $.get("/cases/GetHamlets", { NeighborhoodID: $("#NeighborhoodID").val() }, function (data) {
                $("#HamletID").empty();
                $("#HamletID").append("<option value=''>" + "@(labelSelect)" + "</option>")
                $.each(data, function (index, row) {
                    $("#HamletID").append("<option value='" + row.Id + "'>" + row.Name + "</option>")
                });

                $("#ColonyID").empty();
                $("#ColonyID").append("<option value=''>" + "@(labelSelect)" + "</option>")

                limpiarCampos("");
            });
        });

        $("#HamletID").change(function () {      //  Neighborhood : Aldea
            limpiarCampos("");
        });
    });

    //***************************************
    $('a#MaintenanceM').addClass("active");        //#### CAFQ: 180806
    //***************************************
</script>

Paho/Views/Colony/Delete.cshtml
@model Paho.Models.Colony

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Html.DisplayName((((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelHamlet")))</h4>
    <hr />

    <dl class="dl-horizontal">
        <!-- Country -->
        <dt>
            @Html.DisplayName((((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelCountry"))):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hamlet.Neighborhood.State.Area.Country.Name)
        </dd>
        <!-- Area -->
        <dt>
            @Html.DisplayName((((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelArea"))):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hamlet.Neighborhood.State.Area.Name)
        </dd>
        <!-- State -->
        <dt>
            @Html.DisplayName((((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelState"))):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hamlet.Neighborhood.State.Name)
        </dd>
        <!-- Neighborhood -->
        <dt>
            @Html.DisplayName((((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelNeighborhood"))):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hamlet.Neighborhood.Name)
        </dd>
        <!-- Hamlet -->
        <dt>
            @Html.DisplayName((((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelHamlet"))):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hamlet.Name)
        </dd>
        <!-- Colony -->
        <dt>
            @Html.DisplayName((((Paho.Controllers.ColonyController)this.ViewContext.Controller).getMsg("msgCaselistVigTabGeoLabelColony"))):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <!-- orig_country -->
        <dt>
            @Html.DisplayNameFor(model => model.orig_country):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.orig_country)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

<script type="text/javascript">
    //***************************************
    $('a#MaintenanceM').addClass("active");        //#### CAFQ: 180806
    //***************************************
</script>

Paho/Views/Colony/Index.cshtml
@model PagedList.IPagedList<Paho.Models.Colony>

@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    string labelLatitude = Paho.Controllers.ResourcesM.SgetMessage("msgLatitude", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelLongitude = Paho.Controllers.ResourcesM.SgetMessage("msgLongitude", ViewBag.UsrCtry, ViewBag.UsrCtryLang);

    ViewBag.Title = "Index";
}

<h2>@(Paho.Controllers.ResourcesM.SgetMessage("msgCaselistVigTabGeoLabelColony", ViewBag.UsrCtry, ViewBag.UsrCtryLang))</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Colony", FormMethod.Get))
{
    <p>
        @(Paho.Controllers.ResourcesM.SgetMessage("msgSearchCriteria", ViewBag.UsrCtry, ViewBag.UsrCtryLang)): @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value=@(Paho.Controllers.ResourcesM.SgetMessage("viewHome_btnSearch", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayName((string)(Paho.Controllers.ResourcesM.SgetMessage("msgCaselistVigTabGeoLabelCountry", ViewBag.UsrCtry, ViewBag.UsrCtryLang)))
        </th>
        <th>
            @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgCaselistVigTabGeoLabelColony", ViewBag.UsrCtry, ViewBag.UsrCtryLang),
                                "Index", "Colony", new { sortOrder = ViewBag.ColonyParm, currentFilter = ViewBag.CurrentFilter }, null)
        </th>
        <th>
            @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgCaselistVigTabGeoLabelHamlet", ViewBag.UsrCtry, ViewBag.UsrCtryLang),
                                "Index", "Colony", new { sortOrder = ViewBag.HamletParm, currentFilter = ViewBag.CurrentFilter }, null)
        </th>
        <th>
            @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgCaselistVigTabGeoLabelNeighborhood", ViewBag.UsrCtry, ViewBag.UsrCtryLang),
                                "Index", "Colony", new { sortOrder = ViewBag.NeighborhoodParm, currentFilter = ViewBag.CurrentFilter }, null)
        </th>
        <th>
            @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgCaselistVigTabGeoLabelState", ViewBag.UsrCtry, ViewBag.UsrCtryLang),
                                "Index", "Colony", new { sortOrder = ViewBag.StateParm, currentFilter = ViewBag.CurrentFilter }, null)
        </th>
        <th>
            @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgCaselistVigTabGeoLabelArea", ViewBag.UsrCtry, ViewBag.UsrCtryLang),
                                "Index", "Colony", new { sortOrder = ViewBag.AreaParm, currentFilter = ViewBag.CurrentFilter }, null)
        </th>
        <th>
            @Html.DisplayName((string)Paho.Controllers.ResourcesM.SgetMessage("msgCaselistVigTabGeoLabelOrigCountry", ViewBag.UsrCtry, ViewBag.UsrCtryLang))
        </th>
        <th>
            @Html.DisplayName(labelLatitude)
        </th>
        <th>
            @Html.DisplayName(labelLongitude)
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Hamlet.Neighborhood.State.Area.Country.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hamlet.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hamlet.Neighborhood.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hamlet.Neighborhood.State.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hamlet.Neighborhood.State.Area.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.orig_country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Latitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Longitude)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

<br />
@(Paho.Controllers.ResourcesM.SgetMessage("msgPage", ViewBag.UsrCtry, ViewBag.UsrCtryLang))
@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
@(Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_De", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

<script type="text/javascript">
    //***************************************
    $('a#MaintenanceM').addClass("active");        //#### CAFQ: 180806
    //***************************************
</script>