Paho/Controllers/CatVirusLinajesController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Paho.Models;
using Microsoft.AspNet.Identity;

namespace Paho.Controllers
{
    public class CatVirusLinajesController : ControllerBase
    {
        //private PahoDbContext db = new PahoDbContext();
        int _pageSize = 10;
        // GET: CatVirusLinajes
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.IDSortParm = sortOrder == "id" ? "id_desc" : "id";
            ViewBag.SpaSortParm = string.IsNullOrEmpty(sortOrder) ? "spa_desc" : "";
            ViewBag.EngSortParm = sortOrder == "eng" ? "eng_desc" : "eng";
            ViewBag.OrdenSortParm = sortOrder == "orden" ? "orden_desc" : "orden";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var catalogo = from c in db.CatVirusLinaje select c;
            if (!string.IsNullOrEmpty(searchString))
            {
                catalogo = catalogo.Where(s => s.SPA.Contains(searchString) || s.ENG.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "spa_desc":
                    catalogo = catalogo.OrderByDescending(s => s.SPA);
                    break;
                case "eng":
                    catalogo = catalogo.OrderBy(s => s.ENG);
                    break;
                case "eng_desc":
                    catalogo = catalogo.OrderByDescending(s => s.ENG);
                    break;
                case "orden":
                    catalogo = catalogo.OrderBy(s => s.orden);
                    break;
                case "orden_desc":
                    catalogo = catalogo.OrderByDescending(s => s.orden);
                    break;
                default:
                    catalogo = catalogo.OrderBy(s => s.SPA);
                    break;
            }

            //**** Link Dashboard
            var user = UserManager.FindById(User.Identity.GetUserId());

            string dashbUrl = "", dashbTitle = "";
            List<CatDashboardLink> lista = (from tg in db.CatDashboarLinks
                                            where tg.id_country == user.Institution.CountryID
                                            select tg).ToList();
            if (lista.Count > 0)
            {
                dashbUrl = lista[0].link;
                dashbTitle = lista[0].title;
            }

            ViewBag.DashbUrl = dashbUrl;
            ViewBag.DashbTitle = dashbTitle;
            //****

            int pageSize = _pageSize;
            int pageNumber = (page ?? 1);

            return View(catalogo.ToPagedList(pageNumber, pageSize));

            //return View(db.CatVirusLinaje.ToList());
        }

        // GET: CatVirusLinajes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CatVirusLinaje catVirusLinaje = db.CatVirusLinaje.Find(id);
            if (catVirusLinaje == null)
            {
                return HttpNotFound();
            }
            return View(catVirusLinaje);
        }

        // GET: CatVirusLinajes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CatVirusLinajes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,SPA,ENG,id_country,orden")] CatVirusLinaje catVirusLinaje)
        {
            if (ModelState.IsValid)
            {
                db.CatVirusLinaje.Add(catVirusLinaje);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(catVirusLinaje);
        }

        // GET: CatVirusLinajes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CatVirusLinaje catVirusLinaje = db.CatVirusLinaje.Find(id);
            if (catVirusLinaje == null)
            {
                return HttpNotFound();
            }
            return View(catVirusLinaje);
        }

        // POST: CatVirusLinajes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,SPA,ENG,id_country,orden")] CatVirusLinaje catVirusLinaje)
        {
            if (ModelState.IsValid)
            {
                db.Entry(catVirusLinaje).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(catVirusLinaje);
        }

        // GET: CatVirusLinajes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CatVirusLinaje catVirusLinaje = db.CatVirusLinaje.Find(id);
            if (catVirusLinaje == null)
            {
                return HttpNotFound();
            }
            return View(catVirusLinaje);
        }

        // POST: CatVirusLinajes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CatVirusLinaje catVirusLinaje = db.CatVirusLinaje.Find(id);
            db.CatVirusLinaje.Remove(catVirusLinaje);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Paho/Views/CatVirusLinajes/Create.cshtml
@model Paho.Models.CatVirusLinaje

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@*@(Paho.Controllers.ResourcesM.SgetMessage("msgCatalog", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) - @(Paho.Controllers.ResourcesM.SgetMessage("msgVirusLinaje", ViewBag.UsrCtry, ViewBag.UsrCtryLang))*@</h4>
        <h4>@(Paho.Controllers.CatVirusTypeController.SgetMessage("msgMenuCatVirusLinajeView", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) </h4>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SPA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.SPA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SPA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ENG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.ENG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ENG, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.id_country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.id_country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_country, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.orden, ((string)Paho.Controllers.ResourcesM.SgetMessage("msgOrder", ViewBag.UsrCtry, ViewBag.UsrCtryLang)), htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.orden, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.orden, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@(Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_Crear", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgReturnToList", ViewBag.UsrCtry, ViewBag.UsrCtryLang), "Index", "CatVirusLinajes", new { }, null)
</div>

<script type="text/javascript">
    //***************************************
    $('a#MaintenanceM').addClass("active");        //#### CAFQ: 180806
    //***************************************
</script>  

Paho/Views/CatVirusLinajes/Delete.cshtml
@model Paho.Models.CatVirusLinaje

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>@(Paho.Controllers.CatVirusTypeController.SgetMessage("msgDeleteRecord", ViewBag.UsrCtry, ViewBag.UsrCtryLang))?</h3>
<div>
    <h4>CatVirusLinaje</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SPA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SPA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ENG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ENG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.orden)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.orden)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value=@(Paho.Controllers.CatVirusTypeController.SgetMessage("msgViewCatPopulation_Borrar", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) class="btn btn-default" /> |
            @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgReturnToList", ViewBag.UsrCtry, ViewBag.UsrCtryLang), "Index", "CatVirusLinajes", new { }, null)
        </div>
    }
</div>

<script type="text/javascript">
    //***************************************
    $('a#MaintenanceM').addClass("active");        //#### CAFQ: 180806
    //***************************************
</script>  

Paho/Views/CatVirusLinajes/Details.cshtml
@model Paho.Models.CatVirusLinaje

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CatVirusLinaje</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SPA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SPA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ENG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ENG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.orden)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.orden)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<script type="text/javascript">
    //***************************************
    $('a#MaintenanceM').addClass("active");        //#### CAFQ: 180806
    //***************************************
</script>  

Paho/Views/CatVirusLinajes/Edit.cshtml
@model Paho.Models.CatVirusLinaje

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@(Paho.Controllers.ResourcesM.SgetMessage("msgCatalog", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) - @(Paho.Controllers.ResourcesM.SgetMessage("msgVirusLinaje", ViewBag.UsrCtry, ViewBag.UsrCtryLang))</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.SPA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.SPA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SPA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ENG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.ENG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ENG, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.id_country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_country, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
           @Html.LabelFor(model => model.orden, ((string)Paho.Controllers.ResourcesM.SgetMessage("msgOrder", ViewBag.UsrCtry, ViewBag.UsrCtryLang)), htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.orden, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.orden, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@(Paho.Controllers.CatVirusTypeController.SgetMessage("msgViewSummaryButtonSave", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgReturnToList", ViewBag.UsrCtry, ViewBag.UsrCtryLang), "Index", "CatVirusLinajes", new { }, null)
</div>

<script type="text/javascript">
    //***************************************
    $('a#MaintenanceM').addClass("active");        //#### CAFQ: 180806
    //***************************************
</script>  

Paho/Views/CatVirusLinajes/Index.cshtml
@model PagedList.IPagedList<Paho.Models.CatVirusLinaje>

@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

@*<h2>Index</h2>*@
<h4>@(Paho.Controllers.CatVirusTypeController.SgetMessage("msgMenuCatVirusLinajeView", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) </h4>


<p>
    @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_CrearNuevo", ViewBag.UsrCtry, ViewBag.UsrCtryLang), "Create", "CatVirusLinajes", new { area = "" }, null)
</p>

@using (Html.BeginForm("Index", "CatVirusLinajes", FormMethod.Get))
{
    <p>
        @(Paho.Controllers.ResourcesM.SgetMessage("msgSearchCriteria", ViewBag.UsrCtry, ViewBag.UsrCtryLang)): @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value=@(Paho.Controllers.ResourcesM.SgetMessage("viewHome_btnSearch", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("SPA", "Index", new { sortOrder = ViewBag.SpaSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("ENG", "Index", new { sortOrder = ViewBag.EngSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgOrder", ViewBag.UsrCtry, ViewBag.UsrCtryLang), "Index", "CatVirusSubTypes", new { sortOrder = ViewBag.SpaSortParm, currentFilter = ViewBag.CurrentFilter }, null)
        </th>
        <th>

        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SPA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ENG)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.id_country)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.orden)
        </td>
        <td>
            @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_Editar", ViewBag.UsrCtry, ViewBag.UsrCtryLang), "Edit", "CatVirusLinajes", new { id = item.ID }, null) |
            @Html.ActionLink((string)Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_Borrar", ViewBag.UsrCtry, ViewBag.UsrCtryLang), "Delete", "CatVirusLinajes", new { id = item.ID }, null)
        </td>
    </tr>
}

</table>
@(Paho.Controllers.ResourcesM.SgetMessage("msgPage", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @(Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_De", ViewBag.UsrCtry, ViewBag.UsrCtryLang)) @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

<script type="text/javascript">
    //***************************************
    $('a#MaintenanceM').addClass("active");        //#### CAFQ: 180806
    //***************************************
</script>  