Paho/Controllers/CatCountryController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using Paho.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Paho.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CatCountryController : ControllerBase
    {
        private int _pageSize = 10;

        // GET: Country
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            string language = user.Institution.Country.Language;
            //var countryId = user.Institution.CountryID ?? 0;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.CodeParm = "Code";
            ViewBag.NameParm = "Name";
            ViewBag.ENGParm = "ENG";
            ViewBag.ActiveParm = "Active";

            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;

            var catalogo = from c in db.Countries select c;
            if (!string.IsNullOrEmpty(searchString))
            {
                catalogo = catalogo.Where(s => s.Name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "Code":
                    catalogo = catalogo.OrderBy(s => s.Code);
                    break;
                case "Name":
                    catalogo = catalogo.OrderBy(s => s.Name);
                    break;
                case "ENG":
                    catalogo = catalogo.OrderBy(s => s.ENG);
                    break;
                case "Active":
                    catalogo = catalogo.OrderByDescending(s => s.Active).ThenBy(s => (language == "SPA") ? s.Name : s.ENG);
                    break;
                default:
                    //catalogo = catalogo.OrderBy(s => (language == "SPA") ? s.Name : s.ENG);
                    catalogo = catalogo.OrderByDescending(s => s.Active).ThenBy(s => (language == "SPA") ? s.Name : s.ENG);
                    break;
            }

            int pageSize = _pageSize;
            int pageNumber = (page ?? 1);

            //return View(areas.ToList());
            return View(catalogo.ToPagedList(pageNumber, pageSize));
        }

        // GET: Country/Create
        public ActionResult Create()
        {
            Country country = new Country();

            List<SelectListItem> languageList = new List<SelectListItem>();
            languageList.Add(new SelectListItem { Text = "Español", Value = "SPA" });
            languageList.Add(new SelectListItem { Text = "Ingles", Value = "ENG" });

            country.LanguageList = languageList;

            return View(country);
        }

        // POST: Country/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID, Code, Name, ENG, NumberAdminisDivision, Active, Language")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Countries.Add(country);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(country);
        }

        // GET: Country/Edit/5
        public ActionResult Edit(int? id)
        {
            //var user = UserManager.FindById(User.Identity.GetUserId());
            //var UsrLang = user.Institution.Country.Language;
            //****
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Country country = db.Countries.Find(id);
            if (country == null)
                return HttpNotFound();

            //****
            List<SelectListItem> languageList = new List<SelectListItem>();
            languageList.Add(new SelectListItem { Text = "Español", Value = "SPA" });
            languageList.Add(new SelectListItem { Text = "Ingles", Value = "ENG" });

            country.LanguageList = languageList;

            return View(country);
        }
        
        // POST: Country/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID, Code, Name, ENG, NumberAdminisDivision, Active, Language")] Country country)
        public ActionResult Edit([Bind(Include = "Code, Name, ENG, NumberAdminisDivision, Active, Language")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Entry(country).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.CountryID = new SelectList(db.Countries, "ID", "Code", area.CountryID);           //??????
            return View(country);
        }


        // GET: Country/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Country country = db.Countries.Find(id);
            if (country == null)
                return HttpNotFound();

            return View(country);
        }

        // POST: Country/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Country country = db.Countries.Find(id);
            db.Countries.Remove(country);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

Paho/Views/CatCountry/Create.cshtml
@model Paho.Models.Country

@{
    //string labelEditar = "Editar";
    string LabelReturnToList = (string)Paho.Controllers.ResourcesM.SgetMessage("msgReturnToList", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string LabelButtonSave = Paho.Controllers.CatVirusTypeController.SgetMessage("msgViewSummaryButtonSave", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelCreate = Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_Crear", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelSelect = Paho.Controllers.ResourcesM.SgetMessage("msgGeneralSelect", ViewBag.UsrCtry, ViewBag.UsrCtryLang);

    string labelCodigo = Paho.Controllers.ResourcesM.SgetMessage("msgISOCode", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelNombreSPA = Paho.Controllers.ResourcesM.SgetMessage("msgSpanishName", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelNombreENG = Paho.Controllers.ResourcesM.SgetMessage("msgEnglishName", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelPais = Paho.Controllers.ResourcesM.SgetMessage("msgCountry", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelDivisionesAdminis = Paho.Controllers.ResourcesM.SgetMessage("msgNumberTerritorialPoliticalDivisions", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelActivo = Paho.Controllers.ResourcesM.SgetMessage("msgActive", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelIdioma = Paho.Controllers.ResourcesM.SgetMessage("msgLanguage", ViewBag.UsrCtry, ViewBag.UsrCtryLang);

    
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@labelPais</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Code, labelCodigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, labelNombreSPA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ENG, labelNombreENG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.ENG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ENG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberAdminisDivision, labelDivisionesAdminis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.NumberAdminisDivision, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberAdminisDivision, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, labelActivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, labelIdioma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.DropDownListFor(model => model.Language, Model.LanguageList, labelSelect, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@labelCreate" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(LabelReturnToList, "Index")
</div>

<script type="text/javascript">
    //***************************************
    $('a#MaintenanceM').addClass("active");        //#### CAFQ: 180806
    //***************************************
</script> 

Paho/Views/CatCountry/Delete.cshtml
@model Paho.Models.Country

@{
    string labelCatalogCountry = Paho.Controllers.ResourcesM.SgetMessage("msgMenuCatCountry", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelReturnToList = Paho.Controllers.ResourcesM.SgetMessage("msgReturnToList", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelMsgDeleteRecord = Paho.Controllers.ResourcesM.SgetMessage("msgDeleteRecord", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelDelete = Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_Borrar", ViewBag.UsrCtry, ViewBag.UsrCtryLang);

    string labelCodigo = Paho.Controllers.ResourcesM.SgetMessage("msgISOCode", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelNombreSPA = Paho.Controllers.ResourcesM.SgetMessage("msgSpanishName", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelNombreENG = Paho.Controllers.ResourcesM.SgetMessage("msgEnglishName", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelPais = Paho.Controllers.ResourcesM.SgetMessage("msgCountry", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelDivisionesAdminis = Paho.Controllers.ResourcesM.SgetMessage("msgNumberTerritorialPoliticalDivisions", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelActivo = Paho.Controllers.ResourcesM.SgetMessage("msgActive", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelIdioma = Paho.Controllers.ResourcesM.SgetMessage("msgLanguage", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
}

@{
    ViewBag.Title = labelCatalogCountry;
}

<div>
    <h4>@labelCatalogCountry</h4>
    <hr />
    <h3>@(labelMsgDeleteRecord)?</h3>

    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.Code, labelCodigo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Code, labelNombreSPA)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Code, labelNombreENG)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ENG)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Code, labelDivisionesAdminis)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberAdminisDivision)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Code, labelActivo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Code, labelIdioma)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value=@labelDelete class="btn btn-default" />
        </div>
    }
</div>

<div>
    <br />
    @Html.ActionLink(@labelReturnToList, "Index")
</div>

Paho/Views/CatCountry/Edit.cshtml
@model Paho.Models.Country

@{
    string labelEditar = (string)Paho.Controllers.ResourcesM.SgetMessage("msgEdit", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string LabelReturnToList = (string)Paho.Controllers.ResourcesM.SgetMessage("msgReturnToList", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string LabelButtonSave = Paho.Controllers.CatVirusTypeController.SgetMessage("msgViewSummaryButtonSave", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelSelect = Paho.Controllers.ResourcesM.SgetMessage("msgGeneralSelect", ViewBag.UsrCtry, ViewBag.UsrCtryLang);

    string labelCodigo = Paho.Controllers.ResourcesM.SgetMessage("msgISOCode", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelNombreSPA = Paho.Controllers.ResourcesM.SgetMessage("msgSpanishName", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelNombreENG = Paho.Controllers.ResourcesM.SgetMessage("msgEnglishName", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelPais = Paho.Controllers.ResourcesM.SgetMessage("msgCountry", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelDivisionesAdminis = Paho.Controllers.ResourcesM.SgetMessage("msgNumberTerritorialPoliticalDivisions", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelActivo = Paho.Controllers.ResourcesM.SgetMessage("msgActive", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelIdioma = Paho.Controllers.ResourcesM.SgetMessage("msgLanguage", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
}

@{
    ViewBag.Title = labelEditar;
}

<h2>@labelEditar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@labelPais</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Code, labelCodigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, labelNombreSPA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ENG, labelNombreENG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.ENG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ENG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberAdminisDivision, labelDivisionesAdminis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.NumberAdminisDivision, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberAdminisDivision, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, labelActivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, labelIdioma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.DropDownListFor(model => model.Language, Model.LanguageList, labelSelect, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@(LabelButtonSave) class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink(LabelReturnToList, "Index")
</div>

<script type="text/javascript">
    //***************************************
    $('a#MaintenanceM').addClass("active"); 
    //***************************************
</script>

Paho/Views/CatCountry/Index.cshtml
@model PagedList.IPagedList<Paho.Models.Country>

@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    string labelCatalogCountry = Paho.Controllers.ResourcesM.SgetMessage("msgMenuCatCountry", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    //string labelCatalogName = Paho.Controllers.ResourcesM.SgetMessage("msgMenuCatCloseParametersView", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelCreateNew = Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_CrearNuevo", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelSearchCriteria = Paho.Controllers.ResourcesM.SgetMessage("msgSearchCriteria", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelSubmit = Paho.Controllers.ResourcesM.SgetMessage("viewHome_btnSearch", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelEdit = Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_Editar", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelDelete = Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_Borrar", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelPage = Paho.Controllers.ResourcesM.SgetMessage("msgPage", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelOf = Paho.Controllers.ResourcesM.SgetMessage("msgViewCatPopulation_De", ViewBag.UsrCtry, ViewBag.UsrCtryLang);

    string labelCodigo = Paho.Controllers.ResourcesM.SgetMessage("msgISOCode", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelNombreSPA = Paho.Controllers.ResourcesM.SgetMessage("msgSpanishName", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelNombreENG = Paho.Controllers.ResourcesM.SgetMessage("msgEnglishName", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelPais = Paho.Controllers.ResourcesM.SgetMessage("msgCountry", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelDivisionesAdminis = Paho.Controllers.ResourcesM.SgetMessage("msgNumberTerritorialPoliticalDivisions", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelActivo = Paho.Controllers.ResourcesM.SgetMessage("msgActive", ViewBag.UsrCtry, ViewBag.UsrCtryLang);
    string labelIdioma = Paho.Controllers.ResourcesM.SgetMessage("msgLanguage", ViewBag.UsrCtry, ViewBag.UsrCtryLang);

    ViewBag.Title = labelCatalogCountry;
}

@{
    ViewBag.Title = "Index";
}

<h4>@(labelCatalogCountry)</h4>

<p>
    @Html.ActionLink(labelCreateNew, "Create", "CatCountry", new { area = "" }, null)
</p>

@using (Html.BeginForm("Index", "CatCountry", FormMethod.Get))
{
    <p>
        @(labelSearchCriteria): @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value=@(labelSubmit) />
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayName("ID")
        </th>
        <th>
            @Html.ActionLink(labelCodigo, "Index", new { sortOrder = ViewBag.CodeParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink(labelNombreSPA, "Index", new { sortOrder = ViewBag.NameParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink(labelNombreENG, "Index", new { sortOrder = ViewBag.ENGParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.DisplayName(labelDivisionesAdminis)
        </th>
        <th>
            @Html.ActionLink(labelActivo, "Index", new { sortOrder = ViewBag.ActiveParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.DisplayName(labelIdioma)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ENG)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberAdminisDivision)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Language)
        </td>
        <td>
            @Html.ActionLink(labelEdit, "Edit", new { id=item.ID })  | 
            @*@Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })*@
            @Html.ActionLink(labelDelete, "Delete", new { id = item.ID })
        </td>
    </tr>
}

</table>

<br />
@(labelPage) @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @(labelOf) @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

<script type="text/javascript">
    //***************************************
    $('a#MaintenanceM').addClass("active");
    //***************************************
</script>